function fmt(v) {
  return v.toFixed(4).replace(/\.?0+$/, '');
}

function hexToRgb(hex) {
  const clean = String(hex || '#cccccc').replace('#', '');
  const full = clean.length === 3 ? clean.split('').map((c) => c + c).join('') : clean;
  return [
    parseInt(full.slice(0, 2), 16) / 255,
    parseInt(full.slice(2, 4), 16) / 255,
    parseInt(full.slice(4, 6), 16) / 255,
  ];
}

function safeName(id) {
  return String(id).replace(/[^A-Za-z0-9_-]/g, '_');
}

export function toObj(parts, baseName = 'model') {
  const usable = parts.filter((p) => p.indices.length >= 3);
  const obj = [
    '# Generated by Skyline Forge',
    '# Units: millimetres, Z-up',
    `mtllib ${baseName}.mtl`,
    '',
  ];
  const mtl = ['# Generated by Skyline Forge', ''];

  let vertexOffset = 1;

  for (const part of usable) {
    const name = safeName(part.id);
    const [r, g, b] = hexToRgb(part.color);
    mtl.push(
      `newmtl ${name}`,
      `Kd ${fmt(r)} ${fmt(g)} ${fmt(b)}`,
      `Ka ${fmt(r * 0.2)} ${fmt(g * 0.2)} ${fmt(b * 0.2)}`,
      'Ks 0.05 0.05 0.05',
      'Ns 12',
      'illum 2',
      ''
    );

    obj.push(`o ${name}`, `usemtl ${name}`);

    const pos = part.positions;
    for (let i = 0; i < pos.length; i += 3) {
      obj.push(`v ${fmt(pos[i])} ${fmt(pos[i + 1])} ${fmt(pos[i + 2])}`);
    }
    const idx = part.indices;
    for (let i = 0; i < idx.length; i += 3) {
      obj.push(
        `f ${idx[i] + vertexOffset} ${idx[i + 1] + vertexOffset} ${idx[i + 2] + vertexOffset}`
      );
    }
    obj.push('');
    vertexOffset += pos.length / 3;
  }

  return { obj: obj.join('\n'), mtl: mtl.join('\n') };
}
